version: '2.1'

services:
  nginx:
    container_name: dev.craftzing.remix-streaming-nginx
    image: nginx:1.25-alpine
    restart: unless-stopped
    mem_limit: 32mb
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=reverse-proxy'
      - 'traefik.http.middlewares.devcraftzingremixstreaming.redirectscheme.scheme=https'
      - 'traefik.http.routers.devcraftzingremixstreaming-http.entrypoints=web'
      - 'traefik.http.routers.devcraftzingremixstreaming-http.rule=Host(`remix-streaming.craftzing.dev`)'
      - 'traefik.http.routers.devcraftzingremixstreaming-http.middlewares=devcraftzingremixstreaming'
      - 'traefik.http.routers.devcraftzingremixstreaming-https.entrypoints=websecure'
      - 'traefik.http.routers.devcraftzingremixstreaming-https.rule=Host(`remix-streaming.craftzing.dev`)'
      - 'traefik.http.routers.devcraftzingremixstreaming-https.tls.certresolver=myhttpchallenge'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - reverse-proxy

  node:
    container_name: dev.craftzing.remix-streaming-node
    image: ghcr.io/craftzing/remix-streaming
    restart: unless-stopped
    mem_limit: 128mb

networks:
  reverse-proxy:
    external: true
